-- 军队乡村振兴管理系统 - 数据库初始化脚本（参考用）
-- ⚠️ 实际数据库迁移由 Alembic 管理（backend/alembic/），此文件仅供参考
-- ⚠️ 权威Schema定义在 backend/app/models/ 中，请勿以此文件为准
-- 版本跟随 Alembic head，此注释可能过期

-- 用户表
-- 注意：ORM 模型中字段名为 hashed_password，此处 password_hash 仅为参考
-- SQLite 无 ON UPDATE 自动触发器，updated_at 由应用层（SQLAlchemy onupdate）管理
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE,
    full_name VARCHAR(100),
    role_id INTEGER,
    is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- 角色表
CREATE TABLE IF NOT EXISTS roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255),
    permissions TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 权限表
CREATE TABLE IF NOT EXISTS permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) UNIQUE NOT NULL,
    code VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 帮扶村表
CREATE TABLE IF NOT EXISTS villages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) UNIQUE,
    province VARCHAR(50),
    city VARCHAR(50),
    county VARCHAR(50),
    township VARCHAR(50),
    population INTEGER,
    households INTEGER,
    area REAL,
    description TEXT,
    longitude REAL,
    latitude REAL,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 帮扶学校表
CREATE TABLE IF NOT EXISTS schools (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) UNIQUE,
    village_id INTEGER,
    school_type VARCHAR(50),
    student_count INTEGER,
    teacher_count INTEGER,
    description TEXT,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (village_id) REFERENCES villages(id)
);

-- 帮扶项目表
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(50) UNIQUE,
    village_id INTEGER,
    project_type VARCHAR(50),
    budget REAL DEFAULT 0,
    spent REAL DEFAULT 0,
    start_date DATE,
    end_date DATE,
    status VARCHAR(20) DEFAULT 'planning',
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (village_id) REFERENCES villages(id)
);

-- 经费记录表
CREATE TABLE IF NOT EXISTS funds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER,
    amount REAL NOT NULL,
    fund_type VARCHAR(50),
    source VARCHAR(100),
    description TEXT,
    approved_by INTEGER,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (approved_by) REFERENCES users(id)
);

-- 乡村工作日志表
CREATE TABLE IF NOT EXISTS work_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    village_id INTEGER,
    title VARCHAR(200),
    content TEXT,
    log_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (village_id) REFERENCES villages(id)
);

-- 数据同步日志表
CREATE TABLE IF NOT EXISTS data_sync_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sync_type VARCHAR(20) NOT NULL,
    file_name VARCHAR(255),
    table_name VARCHAR(50),
    records_count INTEGER DEFAULT 0,
    status VARCHAR(20) DEFAULT 'pending',
    error_message TEXT,
    created_by INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- 审计日志表
CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    action VARCHAR(50) NOT NULL,
    resource VARCHAR(100),
    resource_id INTEGER,
    details TEXT,
    ip_address VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 系统配置表（运行时管理设置）
-- 注意：部署级配置使用 .env / Settings 系统（backend/app/core/config.py）
-- 此表仅用于管理员通过 UI 修改的运行时设置，与 .env 配置互补
CREATE TABLE IF NOT EXISTS system_config (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key VARCHAR(100) UNIQUE NOT NULL,
    value TEXT,
    description VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 插入默认角色
INSERT OR IGNORE INTO roles (id, name, description, permissions) VALUES
(1, 'admin', '系统管理员', 'all'),
(2, 'manager', '管理人员', 'read,write,export'),
(3, 'user', '普通用户', 'read');

-- 插入默认管理员用户
-- bcrypt hash of 'admin123' (12 rounds), generated by backend/app/core/security.py
-- 若密码哈希策略变更，需重新生成此哈希值
INSERT OR IGNORE INTO users (id, username, password_hash, email, full_name, role_id, is_active) VALUES
(1, 'admin', '$2b$12$LJ3m4ys3Lk0TSwHlvD.LleRLHrMfLmVORpTvFqDZVBHXXJQxLN/OS', 'admin@example.com', '系统管理员', 1, 1);

-- ============================================================
-- 创建索引（SQLite 不会自动为外键创建索引）
-- 注意：SQLite 不支持 ON UPDATE CURRENT_TIMESTAMP，
-- 所有表的 updated_at 由应用层（SQLAlchemy onupdate）管理
-- ============================================================
-- 唯一约束索引
CREATE INDEX IF NOT EXISTS idx_villages_code ON villages(code);
CREATE INDEX IF NOT EXISTS idx_projects_code ON projects(code);

-- 外键索引（连接查询性能关键）
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_id);
CREATE INDEX IF NOT EXISTS idx_schools_village ON schools(village_id);
CREATE INDEX IF NOT EXISTS idx_projects_village ON projects(village_id);
CREATE INDEX IF NOT EXISTS idx_funds_project ON funds(project_id);
CREATE INDEX IF NOT EXISTS idx_funds_approved_by ON funds(approved_by);
CREATE INDEX IF NOT EXISTS idx_work_logs_user ON work_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_work_logs_village ON work_logs(village_id);
CREATE INDEX IF NOT EXISTS idx_data_sync_logs_created_by ON data_sync_logs(created_by);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id);

-- 查询过滤索引（常用过滤/排序字段）
CREATE INDEX IF NOT EXISTS idx_villages_status ON villages(status);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_type ON projects(project_type);
CREATE INDEX IF NOT EXISTS idx_funds_status ON funds(status);
CREATE INDEX IF NOT EXISTS idx_funds_type ON funds(fund_type);
CREATE INDEX IF NOT EXISTS idx_work_logs_date ON work_logs(log_date);
CREATE INDEX IF NOT EXISTS idx_data_sync_logs_status ON data_sync_logs(status);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);

-- 复合索引（常用多条件查询）
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_action_time ON audit_logs(user_id, action, created_at);
