"""add_village_attachments

Revision ID: 8f7ef51ff62e
Revises: b5c9d3e7f1a2
Create Date: 2026-03-23 19:09:24.165034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7ef51ff62e'
down_revision: Union[str, None] = 'b5c9d3e7f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('village_attachments',
    sa.Column('supported_village_id', sa.Integer(), nullable=False, comment='帮扶村ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='存储路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='文件描述'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='上传者ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supported_village_id'], ['supported_villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('village_attachments', schema=None) as batch_op:
        batch_op.create_index('ix_village_attachments_created_by', ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_village_attachments_id'), ['id'], unique=False)
        batch_op.create_index('ix_village_attachments_village_id', ['supported_village_id'], unique=False)

    op.create_table('fund_field_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False, comment='经费记录ID'),
    sa.Column('field_name', sa.String(length=50), nullable=False, comment='字段名'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='旧值(JSON序列化)'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='新值(JSON序列化)'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='修改人ID'),
    sa.Column('changed_by_name', sa.String(length=100), nullable=True, comment='修改人姓名'),
    sa.Column('changed_at', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_field_changes', schema=None) as batch_op:
        batch_op.create_index('ix_fund_field_changes_changed_at', ['changed_at'], unique=False)
        batch_op.create_index('ix_fund_field_changes_fund_id', ['fund_id'], unique=False)

    op.create_table('fund_operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False, comment='经费记录ID'),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='操作类型: attachment_upload/attachment_delete/...'),
    sa.Column('operation_detail', sa.Text(), nullable=True, comment='操作详情(JSON格式)'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('operator_name', sa.String(length=100), nullable=True, comment='操作人姓名'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='操作时间'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_operation_logs', schema=None) as batch_op:
        batch_op.create_index('ix_fund_operation_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_fund_operation_logs_fund_id', ['fund_id'], unique=False)

    op.create_table('fund_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False, comment='经费记录ID'),
    sa.Column('from_status', sa.String(length=50), nullable=True, comment='原状态'),
    sa.Column('to_status', sa.String(length=50), nullable=False, comment='新状态'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('operator_name', sa.String(length=100), nullable=True, comment='操作人姓名'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='操作备注/原因'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_fund_status_history_fund_id', ['fund_id'], unique=False)
        batch_op.create_index('ix_fund_status_history_operation_time', ['operation_time'], unique=False)

    with op.batch_alter_table('dashboard_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_dashboard_activities_type'))

    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('hidden_dashboard_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hidden_dashboard_activities_activity_id'))

    with op.batch_alter_table('machine_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_codes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_code'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))
        batch_op.drop_index(batch_op.f('ix_projects_status_date'))

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('supported_villages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supported_villages_province'))
        batch_op.drop_index(batch_op.f('ix_supported_villages_tier'))
        batch_op.drop_index(batch_op.f('ix_villages_county_tier'))
        batch_op.drop_index(batch_op.f('ix_villages_province_tier'))
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('system_update_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_update_logs_created_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('system_update_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_update_logs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('supported_villages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_villages_province_tier'), ['province', 'revitalization_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_villages_county_tier'), ['county', 'revitalization_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_supported_villages_tier'), ['revitalization_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_supported_villages_province'), ['province'], unique=False)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_status_date'), ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_code'), ['code'], unique=False)

    with op.batch_alter_table('machine_codes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_machine_codes_organization_id'))

    with op.batch_alter_table('hidden_dashboard_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hidden_dashboard_activities_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('dashboard_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_activities_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_activities_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('fund_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_fund_status_history_operation_time')
        batch_op.drop_index('ix_fund_status_history_fund_id')

    op.drop_table('fund_status_history')
    with op.batch_alter_table('fund_operation_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_fund_operation_logs_fund_id')
        batch_op.drop_index('ix_fund_operation_logs_created_at')

    op.drop_table('fund_operation_logs')
    with op.batch_alter_table('fund_field_changes', schema=None) as batch_op:
        batch_op.drop_index('ix_fund_field_changes_fund_id')
        batch_op.drop_index('ix_fund_field_changes_changed_at')

    op.drop_table('fund_field_changes')
    with op.batch_alter_table('village_attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_village_attachments_village_id')
        batch_op.drop_index(batch_op.f('ix_village_attachments_id'))
        batch_op.drop_index('ix_village_attachments_created_by')

    op.drop_table('village_attachments')
    # ### end Alembic commands ###
