"""
导入模板字段定义 — 集中管理所有模块的导入模板字段元数据。

新增模块时只需在此添加字段定义，ExcelTemplateService 自动支持。
"""
from typing import Dict, List

FieldDef = Dict[str, object]  # {name, key, required, type, desc, options?, width?}

TEMPLATE_FIELDS: Dict[str, List[FieldDef]] = {
    "supported_village": [
        {"name": "帮扶村名称", "key": "village_name", "required": True, "type": "text", "width": 18,
         "desc": "行政村的完整名称，如：红旗村"},
        {"name": "所属省份", "key": "province", "required": True, "type": "text", "width": 12,
         "desc": "如：贵州省"},
        {"name": "所属市/州", "key": "city", "required": True, "type": "text", "width": 12,
         "desc": "如：黔东南州"},
        {"name": "所属县/区", "key": "county", "required": True, "type": "text", "width": 12,
         "desc": "如：从江县"},
        {"name": "所属乡镇", "key": "township", "required": False, "type": "text", "width": 12,
         "desc": "如：丙妹镇"},
        {"name": "帮扶部门", "key": "department", "required": True, "type": "text", "width": 18,
         "desc": "负责帮扶的军队部门，如：陆军第X集团军政治工作部"},
        {"name": "帮扶单位", "key": "support_unit", "required": True, "type": "text", "width": 18,
         "desc": "具体执行帮扶的单位名称"},
        {"name": "帮扶起始年份", "key": "support_year", "required": True, "type": "number", "width": 10,
         "desc": "如：2021"},
        {"name": "是否为三区三州", "key": "is_three_regions", "required": False, "type": "select", "width": 10,
         "desc": "是/否", "options": "是,否"},
        {"name": "是否为边疆地区", "key": "is_border_area", "required": False, "type": "select", "width": 10,
         "desc": "是/否", "options": "是,否"},
        {"name": "是否为振兴梯队", "key": "is_revitalization_tier", "required": False, "type": "select", "width": 10,
         "desc": "是/否", "options": "是,否"},
        {"name": "经度", "key": "longitude", "required": False, "type": "number", "width": 12,
         "desc": "如：108.912"},
        {"name": "纬度", "key": "latitude", "required": False, "type": "number", "width": 12,
         "desc": "如：26.584"},
        {"name": "海拔(米)", "key": "altitude", "required": False, "type": "number", "width": 10,
         "desc": "如：850"},
        {"name": "村域面积(km²)", "key": "area", "required": False, "type": "number", "width": 12,
         "desc": "如：15.6"},
        {"name": "户籍户数", "key": "households", "required": False, "type": "number", "width": 10,
         "desc": "如：356"},
        {"name": "村情描述", "key": "description", "required": False, "type": "text", "width": 30,
         "desc": "简要描述村庄基本情况，不超过500字"},
    ],
    "project": [
        {"name": "项目名称", "key": "name", "required": True, "type": "text", "width": 22,
         "desc": "帮扶项目的完整名称"},
        {"name": "项目类型", "key": "project_type", "required": True, "type": "select", "width": 12,
         "desc": "基础设施/教育/医疗/农业/产业/其他",
         "options": "基础设施,教育,医疗,农业,产业,其他"},
        {"name": "帮扶村名称", "key": "village_name", "required": True, "type": "text", "width": 16,
         "desc": "项目实施的帮扶村名称"},
        {"name": "负责人", "key": "responsible_person", "required": True, "type": "text", "width": 10,
         "desc": "项目负责人姓名"},
        {"name": "联系电话", "key": "contact_phone", "required": False, "type": "text", "width": 14,
         "desc": "项目负责人联系电话"},
        {"name": "开始日期", "key": "start_date", "required": True, "type": "date", "width": 12,
         "desc": "格式 YYYY-MM-DD，如：2025-03-01"},
        {"name": "结束日期", "key": "end_date", "required": False, "type": "date", "width": 12,
         "desc": "格式 YYYY-MM-DD，如：2025-12-31"},
        {"name": "项目状态", "key": "status", "required": True, "type": "select", "width": 10,
         "desc": "规划中/进行中/已完成/已取消",
         "options": "规划中,进行中,已完成,已取消"},
        {"name": "预算金额(万元)", "key": "budget", "required": True, "type": "number", "width": 14,
         "desc": "项目总预算，单位万元，如：150.5"},
        {"name": "负责单位", "key": "responsible_unit", "required": False, "type": "text", "width": 18,
         "desc": "项目实施负责单位全称"},
        {"name": "项目描述", "key": "description", "required": False, "type": "text", "width": 30,
         "desc": "简要描述项目内容和预期效果"},
    ],
    "fund": [
        {"name": "经费名称", "key": "name", "required": True, "type": "text", "width": 22,
         "desc": "经费记录名称"},
        {"name": "经费类型", "key": "fund_type", "required": True, "type": "select", "width": 12,
         "desc": "项目/运营/教育/基础设施/应急/其他",
         "options": "项目,运营,教育,基础设施,应急,其他"},
        {"name": "经费来源", "key": "fund_source", "required": True, "type": "select", "width": 12,
         "desc": "军队/政府/捐赠/企业/其他",
         "options": "军队,政府,捐赠,企业,其他"},
        {"name": "金额(万元)", "key": "amount", "required": True, "type": "number", "width": 14,
         "desc": "经费金额，单位万元，如：50"},
        {"name": "关联项目", "key": "project_name", "required": False, "type": "text", "width": 18,
         "desc": "关联的帮扶项目名称（如有）"},
        {"name": "关联帮扶村", "key": "village_name", "required": False, "type": "text", "width": 16,
         "desc": "关联的帮扶村名称（如有）"},
        {"name": "业务日期", "key": "date", "required": True, "type": "date", "width": 12,
         "desc": "格式 YYYY-MM-DD"},
        {"name": "经费状态", "key": "status", "required": True, "type": "select", "width": 10,
         "desc": "待审批/已批准/已拨付/使用中/已完成/已审计",
         "options": "待审批,已批准,已拨付,使用中,已完成,已审计"},
        {"name": "经办人", "key": "operator", "required": False, "type": "text", "width": 10,
         "desc": "经办人姓名"},
        {"name": "用途说明", "key": "purpose", "required": False, "type": "text", "width": 25,
         "desc": "经费具体用途描述"},
    ],
    "school": [
        {"name": "学校名称", "key": "name", "required": True, "type": "text", "width": 22,
         "desc": "帮扶学校的完整名称"},
        {"name": "学校代码", "key": "code", "required": False, "type": "text", "width": 14,
         "desc": "学校统一社会信用代码或教育机构编码"},
        {"name": "学校类型", "key": "school_type", "required": True, "type": "select", "width": 12,
         "desc": "小学/初中/高中/九年一贯制/完全中学/教学点",
         "options": "小学,初中,高中,九年一贯制,完全中学,教学点"},
        {"name": "所在省份", "key": "province", "required": True, "type": "text", "width": 10,
         "desc": "如：贵州省"},
        {"name": "所在市/州", "key": "city", "required": True, "type": "text", "width": 10,
         "desc": "如：黔东南州"},
        {"name": "所在县/区", "key": "district", "required": True, "type": "text", "width": 10,
         "desc": "如：从江县"},
        {"name": "详细地址", "key": "address", "required": False, "type": "text", "width": 25,
         "desc": "学校详细地址"},
        {"name": "学生人数", "key": "student_count", "required": False, "type": "number", "width": 10,
         "desc": "在校学生总数"},
        {"name": "教师人数", "key": "teacher_count", "required": False, "type": "number", "width": 10,
         "desc": "在职教师总数"},
        {"name": "帮扶状态", "key": "support_status", "required": True, "type": "select", "width": 12,
         "desc": "已帮扶/帮扶中/待帮扶/已完成",
         "options": "已帮扶,帮扶中,待帮扶,已完成"},
        {"name": "帮扶单位", "key": "support_unit", "required": False, "type": "text", "width": 18,
         "desc": "负责帮扶的单位名称"},
        {"name": "校长", "key": "principal", "required": False, "type": "text", "width": 10,
         "desc": "校长姓名"},
        {"name": "联系电话", "key": "phone", "required": False, "type": "text", "width": 14,
         "desc": "学校联系电话"},
        {"name": "帮扶方式", "key": "support_method", "required": False, "type": "text", "width": 20,
         "desc": "如：支教、物资捐赠、基础设施建设"},
    ],
    "policy": [
        {"name": "政策标题", "key": "title", "required": True, "type": "text", "width": 30,
         "desc": "政策法规的完整标题，不超过200字"},
        {"name": "政策文号", "key": "doc_number", "required": False, "type": "text", "width": 18,
         "desc": "如：国办发〔2024〕15号"},
        {"name": "政策级别", "key": "level", "required": True, "type": "select", "width": 12,
         "desc": "国家级/省级/市级/县级",
         "options": "国家级,省级,市级,县级"},
        {"name": "发布机关", "key": "issuing_authority", "required": False, "type": "text", "width": 20,
         "desc": "发布政策的具体机关名称"},
        {"name": "发布日期", "key": "publish_date", "required": False, "type": "date", "width": 12,
         "desc": "格式 YYYY-MM-DD，如：2024-03-15"},
        {"name": "生效日期", "key": "effective_date", "required": False, "type": "date", "width": 12,
         "desc": "格式 YYYY-MM-DD"},
        {"name": "状态", "key": "status", "required": True, "type": "select", "width": 12,
         "desc": "现行有效/已修订/已废止/即将实施",
         "options": "现行有效,已修订,已废止,即将实施"},
        {"name": "关键词", "key": "keywords", "required": False, "type": "text", "width": 20,
         "desc": "多个关键词用逗号分隔"},
        {"name": "政策内容摘要", "key": "content", "required": False, "type": "text", "width": 35,
         "desc": "政策正文内容摘要或全文，不超过2000字"},
    ],
}
